### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mrbipbip** [cedexis/AndroidRadar#10]
Hi, i got this StringIndexOutOfBoundsException on the last AndroidRadar version (0.1.6).
I never had this before today.

```
java.lang.StringIndexOutOfBoundsException: length=8; regionStart=0; regionLength=1106539617
at java.lang.String.startEndAndLength(String.java:588)
at java.lang.String.substring(String.java:1475)
at com.android.okhttp.internal.http.HeaderParser.parseCacheControl(HeaderParser.java:31)
at com.android.okhttp.internal.http.ResponseHeaders.<init>(ResponseHeaders.java:146)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:139)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:179)
at com.cedexis.androidradar.RadarSession.makeHttpRequest(SourceFile:110)
at com.cedexis.androidradar.RadarSession.makeHttpRequest(SourceFile:126)
at com.cedexis.androidradar.RadarProvider.gatherRadarProviders(SourceFile:100)
at com.cedexis.androidradar.RadarSession.run(SourceFile:324)
at com.cedexis.androidradar.RadarService.onHandleIntent(SourceFile:25)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

The line
`at com.cedexis.androidradar.RadarSession.makeHttpRequest(SourceFile:110)`

Is in red in my logcat. If you need, i can share you in private the call i've made before the crash:
`http://radar.cedexis.com/.../providers.json`

Thanks for your help.

**Comment by jakewan** [comment]
Thanks for the issue report.  I forwarded this to our internal ticket system and we'll report back here when the problem is fixed.

**Comment by jmsalcido** [comment]
hi @mrbipbip let us know if in version 0.2.0 it still happens: https://github.com/cedexis/AndroidRadar/releases/tag/v0.2.0

**Comment by mrbipbip** [comment]
Thanks for your feedback. I'll check the new version.

**Comment by jakewan** [comment]
This code path has been removed in the latest version of the library.

https://github.com/cedexis/AndroidRadar/releases/tag/v0.2.6
